apiVersion: 1
datasources:
  - name: LifeDashboard Postgres
    uid: lifedash-postgres
    type: postgres
    access: proxy
    url: db:5432
    user: lifedash
    secureJsonData:
      password: lifedash
    jsonData:
      database: lifedash
      sslmode: disable
      postgresVersion: 1600
